name: Manual release

on:
  workflow_dispatch:
    inputs:
      release_git_sha:
        type: string
        required: true

jobs:
  call-release-base:
    uses: ./.github/workflows/release-base.yml
    with:
      release_git_sha: '${{ inputs.release_git_sha }}'
      release_name: 'current'

