name: Manual release

on:
  workflow_dispatch:
    inputs:
      release_git_sha:
        type: string
        required: true

jobs:
  build_artifacts:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout project
      uses: actions/checkout@v3
      with:
        ref: ''
        # ref: ${{ inputs.release_git_sha }}
    - name: Get project hash
      run: |
        git_hash=$(git rev-parse --short "$GITHUB_SHA")
        echo "git_hash=$git_hash" >> $GITHUB_ENV
    - name: Release files
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "release"
        prerelease: true
        title: "My File"
        files: |
          file.txt
